# Generated by Django 5.0 on 2024-01-01 00:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Document title or filename', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional document description')),
                ('file_path', models.CharField(help_text='Path to the file in object storage', max_length=500, unique=True)),
                ('file_type', models.CharField(help_text='MIME type of the file', max_length=100)),
                ('file_extension', models.CharField(help_text='File extension', max_length=10)),
                ('size', models.BigIntegerField(help_text='File size in bytes')),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Background processing status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(help_text='User who uploaded this document', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'db_table': 'documents',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['uploaded_by'], name='documents_uploaded_by_idx'),
                    models.Index(fields=['file_type'], name='documents_file_type_idx'),
                    models.Index(fields=['file_extension'], name='documents_file_ext_idx'),
                    models.Index(fields=['processing_status'], name='documents_proc_status_idx'),
                    models.Index(fields=['created_at'], name='documents_created_at_idx'),
                ],
            },
        ),
    ]

