# Generated by Django 5.0 on 2024-01-01 00:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('login_failed', 'Failed Login Attempt'), ('document_upload', 'Document Uploaded'), ('document_view', 'Document Viewed'), ('document_download', 'Document Downloaded'), ('document_update', 'Document Updated'), ('document_delete', 'Document Deleted'), ('user_create', 'User Created'), ('user_update', 'User Updated'), ('user_role_change', 'User Role Changed'), ('user_delete', 'User Deleted'), ('password_change', 'Password Changed'), ('system_error', 'System Error')], help_text='Type of action performed', max_length=50)),
                ('resource_type', models.CharField(choices=[('user', 'User'), ('document', 'Document'), ('system', 'System')], help_text='Type of resource affected', max_length=20)),
                ('resource_id', models.IntegerField(blank=True, help_text='ID of the affected resource', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the request', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser user agent string')),
                ('details', models.JSONField(blank=True, default=dict, help_text='Additional context and details')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the action occurred')),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
                'indexes': [
                    models.Index(fields=['user'], name='audit_logs_user_idx'),
                    models.Index(fields=['action'], name='audit_logs_action_idx'),
                    models.Index(fields=['resource_type', 'resource_id'], name='audit_logs_resource_idx'),
                    models.Index(fields=['timestamp'], name='audit_logs_timestamp_idx'),
                    models.Index(fields=['ip_address'], name='audit_logs_ip_address_idx'),
                ],
            },
        ),
    ]

